name: Firebase Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # GitHub token for Actions
          repoToken: ${{ secrets.GITHUB_TOKEN }}

          # Firebase service account JSON (base64 encoded)
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}

          # Your Firebase project ID
          projectId: slims-official-website.web.app

          # Path to the folder containing firebase.json
          entryPoint: firebase

          # Optional: preview channel (remove for live deployment)
          #channelId: staging
