name: NEW Firebase Hostomg Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 3. Deploy using service account with GOOGLE_APPLICATION_CREDENTIALS
      - name: Deploy to Firebase Hosting
        working-directory: Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_TOKEN }}' > "$GOOGLE_APPLICATION_CREDENTIALS"
          firebase deploy --project slims-official-website --only hosting
