name: Firebase Service Hosting Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 3. Deploy using the service account
      - name: Deploy to Firebase Hosting
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_TOKEN }}" > "$HOME/firebase-service-account.json"
          firebase deploy \
            --project slims-official-website \
            --only hosting \
            --token "$(cat $HOME/firebase-service-account.json)"
        working-directory: Firebase
